import './admin-user';
import './profile-edit-profile';
import './profile-edit-password';
import './camp';
import './user';
import './payment-method';
import './bank';
import './method';
import './camp-payments-index';
